[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# Удалили catch-all редирект 200, чтобы API маршруты SSR работали корректно

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(self)"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://mc.yandex.ru https://www.instagram.com https://static.cdninstagram.com https://*.instagram.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://ecom.alfabank.by https://*.instagram.com; frame-src 'self' https://www.instagram.com https://static.cdninstagram.com https://*.instagram.com; font-src 'self' data:; base-uri 'self'; form-action 'self' https://ecom.alfabank.by"

[[headers]]
  for = "/Photo/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/_assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
